### ISSUE TITLE
Migration to Angular 5 - No provider for HttpClient error

### ISSUE THREAD

**Issue by Herzenkin** [sonicoder86/ngx-http-test#9]
After migration to Angular 5 all tests with FakeBackend usages fail with next errors:

> Error: StaticInjectorError[HttpClient]: 
	  StaticInjectorError[HttpClient]: 
	    NullInjectorError: No provider for HttpClient!
	    at _NullInjector.webpackJsonp.../../../core/esm5/core.js._NullInjector.get .../node_modules/@angular/core/esm5/core.js:923:1)
	    at resolveToken .../node_modules/@angular/core/esm5/core.js:1211:1)
	    at tryResolveToken .../node_modules/@angular/core/esm5/core.js:1153:1)
	    at StaticInjector.webpackJsonp.../../../core/esm5/core.js.StaticInjector.get .../node_modules/@angular/core/esm5/core.js:1024:1)
	    at resolveToken .../node_modules/@angular/core/esm5/core.js:1211:1)
	    at tryResolveToken.../node_modules/@angular/core/esm5/core.js:1153:1)
	    at StaticInjector.webpackJsonp.../../../core/esm5/core.js.StaticInjector.get .../node_modules/@angular/core/esm5/core.js:1024:1)
	    at resolveNgModuleDep .../node_modules/@angular/core/esm5/core.js:10585:1)
	    at _createClass .../node_modules/@angular/core/esm5/core.js:10622:1)
	    at _createProviderInstance$1 .../node_modules/@angular/core/esm5/core.js:10596:1)
	
> TypeError: Cannot read property 'expectGet' of undefined
	    at Object.<anonymous> .../src/app/people/person.service.spec.ts:59:10)
	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke .../node_modules/zone.js/dist/zone.js:392:1)
	    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke .../node_modules/zone.js/dist/proxy.js:79:1)
	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke .../node_modules/zone.js/dist/zone.js:391:1)
	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run .../node_modules/zone.js/dist/zone.js:142:1)
	    at Object.<anonymous> .../node_modules/zone.js/dist/jasmine-patch.js:104:1)
	    at ZoneQueueRunner.webpackJsonp.../../../../zone.js/dist/jasmine-patch.js.jasmine.QueueRunner.ZoneQueueRunner.execute .../node_modules/zone.js/dist/jasmine-patch.js:132:1)
	
> TypeError: Cannot read property 'verifyNoPendingRequests' of undefined
	    at Object.<anonymous> .../src/app/people/person.service.spec.ts:54:13)
	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke .../node_modules/zone.js/dist/zone.js:392:1)
	    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke .../node_modules/zone.js/dist/proxy.js:79:1)
	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke .../node_modules/zone.js/dist/zone.js:391:1)
	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run .../node_modules/zone.js/dist/zone.js:142:1)
	    at Object.<anonymous> .../node_modules/zone.js/dist/jasmine-patch.js:104:1)
	    at ZoneQueueRunner.webpackJsonp.../../../../zone.js/dist/jasmine-patch.js.jasmine.QueueRunner.ZoneQueueRunner.execute `.../node_modules/zone.js/dist/jasmine-patch.js:132:1)

The solution of similar [issue](https://github.com/angular/angular/issues/20096) doesn't help.

Any suggestions?

UPD: changed all instances of deprecated "http" service with new "httpClient" one.

**Comment by Herzenkin** [comment]
BTW, are you gonna update dev dependencies fro this project?
